### ISSUE TITLE
画像の保存先について

### ISSUE THREAD

**Issue by Be3751** [Daiki-Shiraki/ez-album#17]
使用用途が限られてて扱う画像枚数は1行事あたり高々100枚くらい？だと思うので、アプリケーションと同じサーバに保存しようかな

**Comment by Be3751** [comment]
研究室から支給されてるGoogleアカウントのGoogle DriveにAPIで保存するのが良い気がしてきた。

**Comment by Daiki-Shiraki** [comment]
一枚一枚保存するよりは、その行事分の仕分けが終わってから一気に保存したほうがいいかな？

**Comment by Be3751** [comment]
以下を参考にすれば良さそう。
- Google Drive APIの利用準備
  - https://developers.google.com/drive/api/quickstart/go
- Google Drive APIを用いたファイルのアップロード（Goのサンプルが見当たらない...）
  - https://developers.google.com/drive/api/guides/manage-uploads

**Comment by Be3751** [comment]
1イベントの枚数は多くても50枚程度なので、即時的にリネームとダウンロードを行う仕様に変更。
よって、一時退避用ストレージとしてのGoogle Drive使用は中止。
