### ISSUE TITLE
フロントエンド：画像のアップロードが失敗する

### ISSUE THREAD

**Issue by Daiki-Shiraki** [Daiki-Shiraki/ez-album#20]
`upload the image!
UploadPhoto.tsx?cc46:30 C:\fakepath\白木大貴.jpg
UploadPhoto.tsx?cc46:31 dshiraki
xhr.js?1a5c:220 `
以下のログとともにアップロードが失敗する

`POST http://localhost:3000/upload 500 (Internal Server Error)
dispatchXhrRequest @ xhr.js?1a5c:220
xhrAdapter @ xhr.js?1a5c:16
dispatchRequest @ dispatchRequest.js?4dc9:58
request @ Axios.js?29fb:109
httpMethod @ Axios.js?29fb:144
wrap @ bind.js?4bea:9
onClickUpload @ UploadPhoto.tsx?cc46:32
callCallback @ react-dom.development.js?ac89:4164
invokeGuardedCallbackDev @ react-dom.development.js?ac89:4213
invokeGuardedCallback @ react-dom.development.js?ac89:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js?ac89:4291
executeDispatch @ react-dom.development.js?ac89:9041
processDispatchQueueItemsInOrder @ react-dom.development.js?ac89:9073
processDispatchQueue @ react-dom.development.js?ac89:9086
dispatchEventsForPlugins @ react-dom.development.js?ac89:9097
eval @ react-dom.development.js?ac89:9288
batchedUpdates$1 @ react-dom.development.js?ac89:26140
batchedUpdates @ react-dom.development.js?ac89:3991
dispatchEventForPluginEventSystem @ react-dom.development.js?ac89:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js?ac89:6465
dispatchEvent @ react-dom.development.js?ac89:6457
dispatchDiscreteEvent @ react-dom.development.js?ac89:6430
127.0.0.1/:1 Uncaught (in promise) AxiosError {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}
XMLHttpRequest.send (async)
dispatchXhrRequest @ xhr.js?1a5c:220
xhrAdapter @ xhr.js?1a5c:16
dispatchRequest @ dispatchRequest.js?4dc9:58
request @ Axios.js?29fb:109
httpMethod @ Axios.js?29fb:144
wrap @ bind.js?4bea:9
onClickUpload @ UploadPhoto.tsx?cc46:32
callCallback @ react-dom.development.js?ac89:4164
invokeGuardedCallbackDev @ react-dom.development.js?ac89:4213
invokeGuardedCallback @ react-dom.development.js?ac89:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js?ac89:4291
executeDispatch @ react-dom.development.js?ac89:9041
processDispatchQueueItemsInOrder @ react-dom.development.js?ac89:9073
processDispatchQueue @ react-dom.development.js?ac89:9086
dispatchEventsForPlugins @ react-dom.development.js?ac89:9097
eval @ react-dom.development.js?ac89:9288
batchedUpdates$1 @ react-dom.development.js?ac89:26140
batchedUpdates @ react-dom.development.js?ac89:3991
dispatchEventForPluginEventSystem @ react-dom.development.js?ac89:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js?ac89:6465
dispatchEvent @ react-dom.development.js?ac89:6457
dispatchDiscreteEvent @ react-dom.development.js?ac89:6430`

**Comment by Daiki-Shiraki** [comment]
CORSの設定が悪いかもなので自分でも確認して見ます

**Comment by Be3751** [comment]
Talend APIを用いたアップロードは可能であることを念の為に確認して、フロントエンドからのアップロードはやはり出来なかった。
アップロード失敗時に、以下のエラーメッセージが出力されていた。
`Access to XMLHttpRequest at 'http://localhost:3000/upload' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by Daiki-Shiraki** [comment]
CORSのエラーは消せたんですけど、依然としてアップロードがうまくいってない
main.go 37行目
cors.Configに
AllowAllOrigins: true,
を追記しました。

**Comment by Be3751** [comment]
原因
- ファイルデータではなくファイルのURLを送信してしまっていた
- AllowAllOrigins: trueの追記により、オリジン限定と全オリジンの許可が衝突してエラー発生していた
