### ISSUE TITLE
名前と画像の対応をDB管理

### ISSUE THREAD

**Issue by Be3751** [Daiki-Shiraki/ez-album#24]
撮影対象者名と画像の対応をRDBで管理する。
加えて、行事名と撮影対象者名の対応を表したテーブルも作成する。
行事名：撮影対象者名で１：多の関係、撮影対象者名：画像で１：多の関係が作れそう。

**Comment by Daiki-Shiraki** [comment]
```mermaid
erDiagram
event ||--o{ target: ""
target ||--o{ picture: ""

event {
  int event_id
  string event_name
}

target {
  int target_id
  string target_name
}

picture {
  int picture_id
  string picture_name
}

```

**Comment by Daiki-Shiraki** [comment]
結果、初めてのupのタイミングですでにdatabaseが生成されていたから
sqlファイルが読み込まれてなかったことが原因だった
--
ので、upする前に所定のディレクトリにsqlファイルを用意してあげる必要がある
このとき、mysqlに接続してdatabaseを削除（DROP）しても意味なかったから
もし一度upしてdatabaseを生成してしまった場合はdataディレクトリの中身を全て削除してあげる必要があるみたい

**Comment by Be3751** [comment]
こっちでも無事DBの初期化とテーブルの作成ができてたよ〜
明日作業する時にPR出してマージしちゃおっか。
