### ISSUE TITLE
MySQLの追加

### ISSUE THREAD

**Issue by Be3751** [Daiki-Shiraki/ez-album#26]
DockerでMySQLの環境を構築しよう。
docker-compose.ymlでMySQLのイメージ（なるべく軽量なバージョンで）を参照して、各種設定値やボリュームの設定をしてほしい。
あと、M1環境で使うならplatformの値をlinux/x86_64にしないとあかんかも。（要調査）

**Comment by Be3751** [comment]
Dockerの勉強になって丁度良いと思うので、よろしく！
これが終わったら、テーブルの作成やMySQLクライアントを用いたDB操作の実装あたりもやっていこう。

**Comment by Daiki-Shiraki** [comment]
> あと、M1環境で使うならplatformの値をlinux/x86_64にしないとあかんかも。（要調査）
おっしゃる通りでした。
[https://www.wakuwakubank.com/posts/869-go-database-sql/](url)
上記の記事参考にMySQLについては操作できるまで確認しました

- だけどGOのModule関連で苦戦しているので確認中death
`error while importing github.com/gin-gonic/gin: module lookup disabled by GOPROXY=off`

**Comment by Daiki-Shiraki** [comment]
と思ったら色々いじってVScode開き直したらエラー消えてた
意味わかんね！ｗ

【やったこと】
`go mod tidy` （脳死でやった、反省はしている）
`go install github.com/gin-gonic/gin@v1.8.1`

**Comment by Be3751** [comment]
MySQLのコンテナは無事作れるようになった感じ？

あと、気になったんやけど、作業する前にmainブランチのpullしてくれてる？
実は昨日airってmoduleが消えてるせいでコンテナ起動時にエラー吐いちゃってたからfixってブランチ用意して修正してmainにマージしておいたんよね。

**Comment by Daiki-Shiraki** [comment]
コンテナは無事建てれてる！（と思う）

> 何をしたかも書いてくれてて良いね。（本当にそれだけ...？って気持ちはあるけども）

割とこれだけだったりする(はず)
一応以下追加です
【やったこと】
`go mod tidy` （脳死でやった、反省はしている）
`go install github.com/gin-gonic/gin@v1.8.1`
エラー変わらなかったけど意図せずVSCodeを開き直したらエラーが消えてた　<- new!!

> あと、気になったんやけど、作業する前にmainブランチのpullしてくれてる？

pullはしてるはず（少なくとも今回の新しい作業ではpullしてる）
けど、自信のpush内容を黙殺してて該当のｍoduleを勝手に消してしまってたのを確認してなかったので以後気をつけます！

**Comment by Daiki-Shiraki** [comment]
module の挙動を全然理解できてないので勉強します
つまりGOの勉強だぁ！

**Comment by Be3751** [comment]
共同開発してて日々更新されるmainとの差分を自身の作業前に取り込む習慣があるなら安心！
ひとまず、今回のタスクはDocker環境でMySQLを入れてくれれば良いだけやから、それが完了してるならpushしてくれて良いよ！

**Comment by Daiki-Shiraki** [comment]
pushしました！ひとまず編集したdocker-compose.ymlだけpushしてある感じ
mysqlの中身のデータ量それなりにあるけどpushしていいか判断できなかったんで今回はとりあえずpushしてないです

以下で動作確認してるけどこれでOKなのかわからん！
`docker exec -it  database bash` 
`mysql -u ユーザ名 -p`
`Enter password:`
>Welcome to the MySQL monitor.  Commands end with ; or \g.
>Your MySQL connection id is 4
>Server version: 5.7.40 MySQL Community Server (GPL).   
>
>Copyright (c) 2000, 2022, Oracle and/or its affiliates.
>
>Oracle is a registered trademark of Oracle Corporation and/or its
>affiliates. Other names may be trademarks of their respective
>owners.

**Comment by Be3751** [comment]
何かpushし忘れてるものはない？
そっちの環境やと上手く起動できてそうやから、環境に差異がある気がする。

### 行ったこと
まず、build時に以下のエラーが出力されるので、databaseディレクトリを作成する。
`unable to prepare context: path "./database" not found`
次に、再度buildすると、今度は以下のエラーが出力される。
`failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3272748938/Dockerfile: no such file or directory`

**Comment by Daiki-Shiraki** [comment]
こっちの環境で確認できなくていまいちよくわかってないねんな…
今回の作業ではdatabase以下のディレクトリ以外は追加してないし（）
このdocker-coｍposeファイルのdatabaseの部分を別ディレクトリで実行しても
問題なく実行できたからマジで何が問題かわかってねぇ…申し訳ない

**Comment by Daiki-Shiraki** [comment]
Dockerfileの場所がわかんないって言ってると思うんですよ（名推理）
databaseに関してはDockerfileないんだけどもしかしてこれってまずい？

**Comment by Be3751** [comment]
今回の教訓としては公式イメージはちゃんとpullしてからupしようってことでCloseします。
