### ISSUE TITLE
データベースのクライアントを作成する

### ISSUE THREAD

**Issue by Daiki-Shiraki** [Daiki-Shiraki/ez-album#32]
CRUDをGoで実装する

**Comment by Daiki-Shiraki** [comment]
DBクライアントを通してCRUDのSQL文を実行できるようにする

**Comment by Be3751** [comment]
ORMには[gorm](https://github.com/go-gorm/gorm)を採用。
@Daiki-Shiraki 
ひとまずgormを使ってレコードの作成をしてみて、実際の挙動を確認してみよう。

**Comment by Be3751** [comment]
#40 のPRで解消されたのでCloseします。
@Daiki-Shiraki このIssueもPRのコメントでメンションしておいてほしかった！
